apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zjcm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zjcm
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zjcm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zjcm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zjcm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zixv-tenant/rhtap-demo-app/hacbs-test-project-zjcm@sha256:ae1070f1b998e961d686d5f7d2fcac457fa239a78221ba6652874c4421f54486
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
